Updating custom project to be align with content editing guide
PDFTron/webviewer-custom-ui pull request #14
Opened 2022-09-07 23:27 UTC by dandara-navarro

2022-09-08 23:10 UTC, dandara-navarro commented
@mparizeau-pdftron , please review these changes.

2022-09-09 00:54 UTC, mparizeau-pdftron requested changes
1. Now that we have inline editing I think we can remove the modal from this sample and we don't need the "edit box" button anymore.

2022-09-09 00:54 UTC, mparizeau-pdftron commented on src/App.js
> +      alert('Content Edit mode is not enable.')
```suggestion
      alert('Content Edit mode is not enabled.')
```

2022-09-09 00:54 UTC, mparizeau-pdftron commented on src/App.js
> +      alert('Content Edit mode is not enable.')
```suggestion
      alert('Content Edit mode is not enabled.')
```

2022-09-09 00:54 UTC, mparizeau-pdftron commented on src/App.js
> +          <button onClick={endEditingContent} title="End editx mode">
```suggestion
          <button onClick={endEditingContent} title="End edit mode">
```

2022-09-09 00:54 UTC, mparizeau-pdftron commented on src/App.js
> +    contentEditManager.endContentEditMode();
I think it would be cleaner too if we also switch to the EDIT tool.

2022-09-10 01:06 UTC, mparizeau-pdftron requested changes
Since we're not using the modal anymore can you remove all the related code. I still see the `<Modal>` element in the render, we can remove the `simple-react-modal` dependency from package.json, same with all the Quill stuff. All variables and functions related to it can be removed as well.

2022-09-10 01:06 UTC, mparizeau-pdftron commented on src/App.js
> +    documentViewer.setToolMode(window.Core.Tools.ToolNames.EDIT)
This should be the following. Right now it's not working.
```suggestion
    documentViewer.setToolMode(documentViewer.getTool(window.Core.Tools.ToolNames.EDIT));
```

2022-09-15 18:30 UTC, mparizeau-pdftron approved these changes

2022-09-15 18:30 UTC, merged